---

- include: install.yml

- include: master.yml
  when: ( inventory_hostname in groups['kubernetes-master'] )

- include: node.yml
  when: ( inventory_hostname in groups['kubernetes-nodes'] )