---

- debug: msg="Server"

- name: enable services
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

- name: start services
  service: 
    name: "{{ item }}"
    state: started
  with_items:
    - rpc-statd
    - nfs-idmapd

- name: add NFS share to /etc/export
  lineinfile: 
    dest: "/etc/exports" 
    regexp: "^{{ item.path }} " 
    line: "{{ item.path }} {{ item.export }}" 
    create: yes
  with_items: "{{ nfs_exports }}"
  register: nfs_exports_result

- name: Restart NFS server service
  service: 
    name: nfs-server
    state: restarted
  when: nfs_exports_result|changed

- name: enable firewalld for NFS Server
  firewalld:
    service: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  with_items:
    - mountd
    - rpc-bind
    - nfs